# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IT1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Localspotpic',
        ),
    ]
